# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 12:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(b'^[\\w:]+$', b'Characters must match regex [\\w:]+', b'invalid')])),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='classes',
            field=models.ManyToManyField(blank=True, to='puppet.Class'),
        ),
        migrations.AddField(
            model_name='node',
            name='classes',
            field=models.ManyToManyField(blank=True, to='puppet.Class'),
        ),
    ]
