# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0002_auto_20170823_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='groups', to='puppet.Class'),
        ),
        migrations.AlterField(
            model_name='node',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='nodes', to='puppet.Class'),
        ),
        migrations.AlterField(
            model_name='node',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='nodes', to='puppet.Group'),
        ),
    ]
