# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0002_auto_20170223_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='parents',
            field=models.ManyToManyField(blank=True, to='puppet.Group'),
        ),
    ]
